// Source: murdoku-logic-engine example-cases/easy-04.ts (commit 9264e2a623165af9e83382a2cd66fa94fe66bda5)
// — real case name not used elsewhere in this file.
import type { MurdokuDefinition } from 'murdoku-logic-engine';
import type { RoyalInquestSkin } from '../skin';

export const title = "The Riding Master's Secret";

export const definition: MurdokuDefinition = {
  id: 'easy-04',
  version: 1,
  rows: 9,
  columns: 9,
  difficulty: 2,
  // Categories mirror the gendered wording of the source case's real clues ("he"/"she").
  suspects: [
    { id: 'A', label: 'A', category: 'woman' },
    { id: 'B', label: 'B', category: 'man' },
    { id: 'C', label: 'C', category: 'woman' },
    { id: 'D', label: 'D', category: 'woman' },
    { id: 'E', label: 'E', category: 'woman' },
    { id: 'F', label: 'F', category: 'man' },
    { id: 'G', label: 'G', category: 'woman' },
    { id: 'H', label: 'H', category: 'woman' },
    { id: 'I', label: 'I', category: 'woman', isVictim: true },
  ],
  rooms: [
    { id: 'room-1', label: 'Room 1' },
    { id: 'room-2', label: 'Room 2' },
    { id: 'room-3', label: 'Room 3' },
    { id: 'room-4', label: 'Room 4' },
  ],
  props: [
    { id: 'asset-1-1', kind: 'decorative' },
    { id: 'asset-2-1', kind: 'decorative' },
    { id: 'asset-3*-1', kind: 'seat' },
    { id: 'asset-3*-2', kind: 'seat' },
    { id: 'asset-4*-1', kind: 'seat' },
  ],
  cells: [
    { position: { row: 0, column: 0 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 1 }, roomId: 'room-3', blocked: false },
    { position: { row: 0, column: 2 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 3 }, roomId: 'room-2', blocked: true },
    { position: { row: 0, column: 4 }, roomId: 'room-2', blocked: true },
    { position: { row: 0, column: 5 }, roomId: 'room-2', blocked: true },
    { position: { row: 0, column: 6 }, roomId: 'room-2', blocked: false },
    { position: { row: 0, column: 7 }, roomId: 'room-2', blocked: false },
    { position: { row: 0, column: 8 }, roomId: 'room-2', blocked: false },
    { position: { row: 1, column: 0 }, roomId: 'room-3', blocked: true, propId: 'asset-1-1' },
    { position: { row: 1, column: 1 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 2 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 3 }, roomId: 'room-2', blocked: true },
    { position: { row: 1, column: 4 }, roomId: 'room-2', blocked: true },
    { position: { row: 1, column: 5 }, roomId: 'room-2', blocked: true },
    { position: { row: 1, column: 6 }, roomId: 'room-2', blocked: true },
    { position: { row: 1, column: 7 }, roomId: 'room-2', blocked: true },
    { position: { row: 1, column: 8 }, roomId: 'room-2', blocked: true },
    { position: { row: 2, column: 0 }, roomId: 'room-3', blocked: true },
    { position: { row: 2, column: 1 }, roomId: 'room-3', blocked: false },
    { position: { row: 2, column: 2 }, roomId: 'room-3', blocked: true },
    { position: { row: 2, column: 3 }, roomId: 'room-2', blocked: false },
    { position: { row: 2, column: 4 }, roomId: 'room-2', blocked: false },
    { position: { row: 2, column: 5 }, roomId: 'room-2', blocked: false },
    { position: { row: 2, column: 6 }, roomId: 'room-2', blocked: false },
    { position: { row: 2, column: 7 }, roomId: 'room-2', blocked: false },
    { position: { row: 2, column: 8 }, roomId: 'room-2', blocked: false, propId: 'asset-3*-2' },
    { position: { row: 3, column: 0 }, roomId: 'room-3', blocked: false },
    { position: { row: 3, column: 1 }, roomId: 'room-3', blocked: false },
    { position: { row: 3, column: 2 }, roomId: 'room-3', blocked: false },
    { position: { row: 3, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 4 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 5 }, roomId: 'room-1', blocked: true },
    { position: { row: 3, column: 6 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 7 }, roomId: 'room-2', blocked: false },
    { position: { row: 3, column: 8 }, roomId: 'room-2', blocked: true },
    { position: { row: 4, column: 0 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 2 }, roomId: 'room-1', blocked: false, propId: 'asset-4*-1' },
    { position: { row: 4, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 4 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 5 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 6 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 7 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 8 }, roomId: 'room-4', blocked: false },
    { position: { row: 5, column: 0 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 1 }, roomId: 'room-1', blocked: true },
    { position: { row: 5, column: 2 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 4 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 5 }, roomId: 'room-1', blocked: false, propId: 'asset-3*-1' },
    { position: { row: 5, column: 6 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 7 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 8 }, roomId: 'room-4', blocked: false },
    { position: { row: 6, column: 0 }, roomId: 'room-4', blocked: false },
    { position: { row: 6, column: 1 }, roomId: 'room-1', blocked: true },
    { position: { row: 6, column: 2 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 4 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 5 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 6 }, roomId: 'room-1', blocked: true },
    { position: { row: 6, column: 7 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 8 }, roomId: 'room-4', blocked: false },
    { position: { row: 7, column: 0 }, roomId: 'room-4', blocked: true },
    { position: { row: 7, column: 1 }, roomId: 'room-4', blocked: false },
    { position: { row: 7, column: 2 }, roomId: 'room-1', blocked: false },
    { position: { row: 7, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 7, column: 4 }, roomId: 'room-1', blocked: true },
    { position: { row: 7, column: 5 }, roomId: 'room-1', blocked: false },
    { position: { row: 7, column: 6 }, roomId: 'room-4', blocked: false },
    { position: { row: 7, column: 7 }, roomId: 'room-4', blocked: true },
    { position: { row: 7, column: 8 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 0 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 1 }, roomId: 'room-4', blocked: true },
    { position: { row: 8, column: 2 }, roomId: 'room-4', blocked: true, propId: 'asset-2-1' },
    { position: { row: 8, column: 3 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 4 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 5 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 6 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 7 }, roomId: 'room-4', blocked: false },
    { position: { row: 8, column: 8 }, roomId: 'room-4', blocked: true },
  ],
  // Christa's clue ("one column west of a woman sitting on a horse") splits in two: axis-offset-from
  // carries the positional half, referencing E directly — on the corrected board E (in the Stable,
  // per her own real clue) is exactly the suspect who ends up one column east of Christa and on the
  // second horse-seat, so no invented stand-in is needed here. category-on-prop carries the unnamed
  // "a woman was on that horse" half.
  clues: [
    {
      id: 'clue-1',
      text: 'A is beside asset-2-1',
      predicate: { type: 'near-prop', suspectId: 'A', propId: 'asset-2-1' },
    },
    {
      id: 'clue-2',
      text: 'B is beside asset-1-1',
      predicate: { type: 'near-prop', suspectId: 'B', propId: 'asset-1-1' },
    },
    {
      id: 'clue-3',
      text: 'C is exactly 1 column west of E',
      predicate: { type: 'axis-offset-from', subjectSuspectId: 'C', referenceSuspectId: 'E', axis: 'column', offset: -1 },
    },
    {
      id: 'clue-3b',
      text: 'A woman is on asset-3*-2',
      predicate: { type: 'category-on-prop', category: 'woman', propId: 'asset-3*-2' },
    },
    {
      id: 'clue-4',
      text: 'D is in column 4',
      predicate: { type: 'exact-column', suspectId: 'D', column: 4 },
    },
    {
      id: 'clue-5',
      text: 'E is in room-2',
      predicate: { type: 'exact-room', suspectId: 'E', roomId: 'room-2' },
    },
    {
      id: 'clue-6',
      text: 'F is on asset-3*-1',
      predicate: { type: 'on-prop', suspectId: 'F', propId: 'asset-3*-1' },
    },
    {
      id: 'clue-7',
      text: 'F is in room-1',
      predicate: { type: 'exact-room', suspectId: 'F', roomId: 'room-1' },
    },
    {
      id: 'clue-8',
      text: 'G is in room-3',
      predicate: { type: 'exact-room', suspectId: 'G', roomId: 'room-3' },
    },
    {
      id: 'clue-9',
      text: 'G and B are in the same room',
      predicate: { type: 'same-room', firstSuspectId: 'G', secondSuspectId: 'B' },
    },
    {
      id: 'clue-10',
      text: 'H is on asset-4*-1',
      predicate: { type: 'on-prop', suspectId: 'H', propId: 'asset-4*-1' },
    },
    {
      id: 'clue-11',
      text: '(supplemental) C is in row 0',
      predicate: { type: 'exact-row', suspectId: 'C', row: 0 },
    },
    {
      id: 'clue-12',
      text: '(supplemental) D is in row 6',
      predicate: { type: 'exact-row', suspectId: 'D', row: 6 },
    },
    {
      id: 'clue-13',
      text: '(supplemental) E is in row 2',
      predicate: { type: 'exact-row', suspectId: 'E', row: 2 },
    },
    {
      id: 'clue-14',
      text: '(supplemental) E is in column 8',
      predicate: { type: 'exact-column', suspectId: 'E', column: 8 },
    },
    {
      id: 'clue-15',
      text: '(supplemental) G is in row 3',
      predicate: { type: 'exact-row', suspectId: 'G', row: 3 },
    },
    {
      id: 'clue-16',
      text: '(supplemental) G is in column 0',
      predicate: { type: 'exact-column', suspectId: 'G', column: 0 },
    },
  ],
  murdererId: 'A',
  solution: {
    A: { row: 8, column: 3 },
    B: { row: 1, column: 1 },
    C: { row: 0, column: 7 },
    D: { row: 6, column: 4 },
    E: { row: 2, column: 8 },
    F: { row: 5, column: 5 },
    G: { row: 3, column: 0 },
    H: { row: 4, column: 2 },
    I: { row: 7, column: 6 },
  },
};

export const skin: RoyalInquestSkin = {
  suspects: {
    A: { name: 'Lady Aveline', avatarId: 'noblewoman' },
    B: { name: 'Lord Bram', avatarId: 'nobleman' },
    C: { name: 'Lady Cerys', avatarId: 'royal-consort' },
    D: { name: 'Dame Delyth', avatarId: 'maid' },
    E: { name: 'Mistress Esme', avatarId: 'noblewoman' },
    F: { name: 'Sir Fenrir', avatarId: 'knight' },
    G: { name: 'Goodwife Gwen', avatarId: 'maid' },
    H: { name: 'Lady Hollis', avatarId: 'royal-consort' },
    I: { name: 'Lady Isolde', avatarId: 'noblewoman' },
  },
  rooms: {
    'room-1': { name: 'the Training Yard', environment: 'room' },
    'room-2': { name: 'the Royal Stables', environment: 'room' },
    'room-3': { name: 'the Tack Room', environment: 'room' },
    'room-4': { name: 'the Pasture', environment: 'garden' },
  },
  props: {
    'asset-1-1': { assetId: 'dining-table' },
    'asset-2-1': { assetId: 'wooden-planter' },
    'asset-3*-1': { assetId: 'simple-chair' },
    'asset-3*-2': { assetId: 'wooden-bench' },
    'asset-4*-1': { assetId: 'wooden-bench' },
  },
};
