// Source: murdoku-logic-engine example-cases/easy-01.ts (commit 9264e2a623165af9e83382a2cd66fa94fe66bda5)
// — real case name not used elsewhere in this file.
import type { MurdokuDefinition } from 'murdoku-logic-engine';
import type { RoyalInquestSkin } from '../skin';

export const title = 'The Greenhouse Plot';

export const definition: MurdokuDefinition = {
  id: 'easy-01',
  version: 1,
  rows: 7,
  columns: 7,
  difficulty: 2,
  suspects: [
    { id: 'A', label: 'A' },
    { id: 'B', label: 'B' },
    { id: 'C', label: 'C' },
    { id: 'D', label: 'D' },
    { id: 'E', label: 'E' },
    { id: 'F', label: 'F' },
    { id: 'G', label: 'G', isVictim: true },
  ],
  rooms: [
    { id: 'room-1', label: 'Room 1' },
    { id: 'room-2', label: 'Room 2' },
    { id: 'room-3', label: 'Room 3' },
  ],
  props: [
    { id: 'asset-1-1', kind: 'decorative' },
    { id: 'asset-2*-1', kind: 'seat' },
    { id: 'asset-3*-1', kind: 'seat' },
  ],
  cells: [
    { position: { row: 0, column: 0 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 1 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 2 }, roomId: 'room-3', blocked: false },
    { position: { row: 0, column: 3 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 4 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 5 }, roomId: 'room-3', blocked: true },
    { position: { row: 0, column: 6 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 0 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 1 }, roomId: 'room-3', blocked: false, propId: 'asset-3*-1' },
    { position: { row: 1, column: 2 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 3 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 4 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 5 }, roomId: 'room-3', blocked: false },
    { position: { row: 1, column: 6 }, roomId: 'room-3', blocked: false },
    { position: { row: 2, column: 0 }, roomId: 'room-1', blocked: true },
    { position: { row: 2, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 2, column: 2 }, roomId: 'room-1', blocked: true },
    { position: { row: 2, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 2, column: 4 }, roomId: 'room-3', blocked: false },
    { position: { row: 2, column: 5 }, roomId: 'room-3', blocked: false, propId: 'asset-2*-1' },
    { position: { row: 2, column: 6 }, roomId: 'room-3', blocked: true },
    { position: { row: 3, column: 0 }, roomId: 'room-1', blocked: true },
    { position: { row: 3, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 2 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 3, column: 4 }, roomId: 'room-2', blocked: false },
    { position: { row: 3, column: 5 }, roomId: 'room-2', blocked: false },
    { position: { row: 3, column: 6 }, roomId: 'room-2', blocked: true },
    { position: { row: 4, column: 0 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 4, column: 2 }, roomId: 'room-1', blocked: true },
    { position: { row: 4, column: 3 }, roomId: 'room-1', blocked: true },
    { position: { row: 4, column: 4 }, roomId: 'room-2', blocked: true },
    { position: { row: 4, column: 5 }, roomId: 'room-2', blocked: false },
    { position: { row: 4, column: 6 }, roomId: 'room-2', blocked: true, propId: 'asset-1-1' },
    { position: { row: 5, column: 0 }, roomId: 'room-1', blocked: true },
    { position: { row: 5, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 2 }, roomId: 'room-1', blocked: true },
    { position: { row: 5, column: 3 }, roomId: 'room-1', blocked: false },
    { position: { row: 5, column: 4 }, roomId: 'room-2', blocked: false },
    { position: { row: 5, column: 5 }, roomId: 'room-2', blocked: false },
    { position: { row: 5, column: 6 }, roomId: 'room-2', blocked: false },
    { position: { row: 6, column: 0 }, roomId: 'room-1', blocked: true },
    { position: { row: 6, column: 1 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 2 }, roomId: 'room-1', blocked: false },
    { position: { row: 6, column: 3 }, roomId: 'room-1', blocked: true },
    { position: { row: 6, column: 4 }, roomId: 'room-2', blocked: false },
    { position: { row: 6, column: 5 }, roomId: 'room-2', blocked: false },
    { position: { row: 6, column: 6 }, roomId: 'room-2', blocked: false },
  ],
  clues: [
    {
      id: 'clue-1',
      text: 'A is beside asset-1-1',
      predicate: { type: 'near-prop', suspectId: 'A', propId: 'asset-1-1' },
    },
    {
      id: 'clue-2',
      text: 'B is in room-3',
      predicate: { type: 'exact-room', suspectId: 'B', roomId: 'room-3' },
    },
    {
      id: 'clue-3',
      text: 'C is on asset-2*-1',
      predicate: { type: 'on-prop', suspectId: 'C', propId: 'asset-2*-1' },
    },
    {
      id: 'clue-4',
      text: 'D is on asset-3*-1',
      predicate: { type: 'on-prop', suspectId: 'D', propId: 'asset-3*-1' },
    },
    {
      id: 'clue-5',
      text: 'E is in column 1',
      predicate: { type: 'exact-column', suspectId: 'E', column: 0 },
    },
    {
      id: 'clue-6',
      text: 'F is in room-1',
      predicate: { type: 'exact-room', suspectId: 'F', roomId: 'room-1' },
    },
    {
      id: 'clue-7',
      text: 'F is in the same room as A or E',
      predicate: {
        type: 'one-of',
        options: [
          { type: 'same-room', firstSuspectId: 'F', secondSuspectId: 'A' },
          { type: 'same-room', firstSuspectId: 'F', secondSuspectId: 'E' },
        ],
      },
    },
    {
      id: 'clue-8',
      text: '(supplemental) A is in row 6',
      predicate: { type: 'exact-row', suspectId: 'A', row: 5 },
    },
    {
      id: 'clue-9',
      text: '(supplemental) B is in row 1',
      predicate: { type: 'exact-row', suspectId: 'B', row: 0 },
    },
    {
      id: 'clue-10',
      text: '(supplemental) B is in column 3',
      predicate: { type: 'exact-column', suspectId: 'B', column: 2 },
    },
    {
      id: 'clue-11',
      text: '(supplemental) E is in row 5',
      predicate: { type: 'exact-row', suspectId: 'E', row: 4 },
    },
    {
      id: 'clue-12',
      text: '(supplemental) F is in row 4',
      predicate: { type: 'exact-row', suspectId: 'F', row: 3 },
    },
    {
      id: 'clue-13',
      text: '(supplemental) F is in column 4',
      predicate: { type: 'exact-column', suspectId: 'F', column: 3 },
    },
  ],
  murdererId: 'A',
  solution: {
    A: { row: 5, column: 6 },
    B: { row: 0, column: 2 },
    C: { row: 2, column: 5 },
    D: { row: 1, column: 1 },
    E: { row: 4, column: 0 },
    F: { row: 3, column: 3 },
    G: { row: 6, column: 4 },
  },
};

export const skin: RoyalInquestSkin = {
  suspects: {
    A: { name: 'Gardener Alaric', avatarId: 'gardener' },
    B: { name: 'Mistress Briony', avatarId: 'maid' },
    C: { name: 'Father Cassian', avatarId: 'priest' },
    D: { name: 'Dame Delphine', avatarId: 'noblewoman' },
    E: { name: 'Ewan the Merchant', avatarId: 'merchant' },
    F: { name: 'Steward Fenwick', avatarId: 'steward' },
    G: { name: 'Old Gwyn', avatarId: 'cook' },
  },
  rooms: {
    'room-1': { name: 'the Greenhouse Floor', environment: 'garden' },
    'room-2': { name: 'the Counting Room', environment: 'garden' },
    'room-3': { name: 'the Potting Shed', environment: 'room' },
  },
  props: {
    'asset-1-1': { assetId: 'wooden-planter' },
    'asset-2*-1': { assetId: 'wooden-bench' },
    'asset-3*-1': { assetId: 'simple-chair' },
  },
};
