import type { InquestDefinition, InquestPredicate } from '../../src/features/royal-inquest/types';

export interface EmitResult {
  fileContent: string;
  exportName: string;
}

function camelCase(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_match, char: string) => char.toUpperCase());
}

function quoteKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : `'${key}'`;
}

function tsString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function serializeValue(value: unknown): string {
  if (typeof value === 'string') return tsString(value);
  return String(value);
}

function serializePredicate(predicate: InquestPredicate): string {
  const entries = Object.entries(predicate).map(([key, value]) => `${quoteKey(key)}: ${serializeValue(value)}`);
  return `{ ${entries.join(', ')} }`;
}

/**
 * Serializes a generated `InquestDefinition` into a `.ts` source string matching the shape/style of
 * the hand-authored files under `src/features/royal-inquest/levels/` (see `hollowmereLodge.ts`):
 * same import lines, `decorativePropsByPosition`/`seatPropsByPosition`/`propsByPosition`/
 * `blockedCells` split, a `chamberByPosition` 2D literal, `cells` built via `.flatMap`, and a
 * trailing `export const <camelCaseId>: InquestDefinition = {...}`. Deliberately close to that
 * shape (rather than a generic JSON dump) so a human can freely hand-edit the output afterward
 * without it reading as foreign to the rest of the level files.
 */
export function emitLevelFile(definition: InquestDefinition): EmitResult {
  const exportName = camelCase(definition.id);

  const decorativeLines: string[] = [];
  const seatLines: string[] = [];
  for (const cell of definition.cells) {
    if (!cell.propId) continue;
    const key = `${cell.position.row}:${cell.position.column}`;
    const line = `  '${key}': ${tsString(cell.propId)},`;
    if (cell.blocked) decorativeLines.push(line);
    else seatLines.push(line);
  }

  const chamberRows: string[] = [];
  for (let row = 0; row < definition.rows; row += 1) {
    const rowCells = definition.cells
      .filter((cell) => cell.position.row === row)
      .sort((a, b) => a.position.column - b.position.column)
      .map((cell) => tsString(cell.chamberId));
    chamberRows.push(`  [${rowCells.join(', ')}],`);
  }

  const chamberEnvironmentsLines = Object.entries(definition.chamberEnvironments).map(
    ([id, environment]) => `  ${quoteKey(id)}: ${tsString(environment)},`,
  );
  const chamberNamesLines = Object.entries(definition.chamberNames).map(([id, name]) => `  ${quoteKey(id)}: ${tsString(name)},`);

  const charactersLines = definition.characters.map((character) => {
    const parts = [
      `id: ${tsString(character.id)}`,
      `name: ${tsString(character.name)}`,
      `portraitLabel: ${tsString(character.portraitLabel)}`,
      `avatarId: ${tsString(character.avatarId)}`,
    ];
    if (character.category) parts.push(`category: ${tsString(character.category)}`);
    if (character.isVictim) parts.push('isVictim: true');
    return `    { ${parts.join(', ')} },`;
  });

  const cluesLines = definition.clues.map(
    (clue) =>
      `    {\n      id: ${tsString(clue.id)},\n      text: ${tsString(clue.text)},\n      predicate: ${serializePredicate(clue.predicate)},\n    },`,
  );

  const solutionLines = Object.entries(definition.solution).map(
    ([id, position]) => `  ${quoteKey(id)}: { row: ${position.row}, column: ${position.column} },`,
  );

  const fileContent = `import type { GridPosition } from '../../../shared/geometry';
import type { PropAssetId } from '../../../assets/royal-inquest/manifest';
import type { CharacterId, InquestCell, InquestDefinition } from '../types';

// Generated by tools/royal-inquest-generator (seed-reproducible - see
// docs/royal-inquest/authoring/level-generator.cave.md). Free to hand-edit after generation; the
// generator itself does not read this file back.
const decorativePropsByPosition: Record<string, PropAssetId> = {
${decorativeLines.length > 0 ? decorativeLines.join('\n') : '  // none'}
};

const seatPropsByPosition: Record<string, PropAssetId> = {
${seatLines.length > 0 ? seatLines.join('\n') : '  // none'}
};

const propsByPosition: Record<string, PropAssetId> = {
  ...decorativePropsByPosition,
  ...seatPropsByPosition,
};

const blockedCells = new Set(Object.keys(decorativePropsByPosition));

const chamberByPosition = [
${chamberRows.join('\n')}
] as const;

const chamberEnvironments: InquestDefinition['chamberEnvironments'] = {
${chamberEnvironmentsLines.join('\n')}
};

const chamberNames: InquestDefinition['chamberNames'] = {
${chamberNamesLines.join('\n')}
};

const cells: InquestCell[] = chamberByPosition.flatMap((row, rowIndex) =>
  row.map((chamberId, columnIndex) => {
    const key = \`\${rowIndex}:\${columnIndex}\`;
    return {
      position: { row: rowIndex, column: columnIndex },
      chamberId,
      blocked: blockedCells.has(key),
      ...(propsByPosition[key] ? { propId: propsByPosition[key] } : {}),
    };
  }),
);

const solution: Record<CharacterId, GridPosition> = {
${solutionLines.join('\n')}
};

export const ${exportName}: InquestDefinition = {
  id: ${tsString(definition.id)},
  title: ${tsString(definition.title)},
  definitionVersion: 1,
  difficulty: ${definition.difficulty},
  rows: ${definition.rows},
  columns: ${definition.columns},
  characters: [
${charactersLines.join('\n')}
  ],
  cells,
  chamberEnvironments,
  chamberNames,
  clues: [
${cluesLines.join('\n')}
  ],
  traitorId: ${tsString(definition.traitorId)},
  solution,
};

// Alias so \`npm run inquest:solve -- --file <this file>\` (which looks for a \`definition\` or
// \`default\` export) can load this draft directly, before it's registered in levels/index.ts under
// its real name above.
export const definition = ${exportName};
`;

  return { fileContent, exportName };
}
